pipeline {
  agent {
    docker {
      image 'node:6-alpine'
      args '-p 3000:3000'
    }
  }
  stage('Setup') {
      steps {
        // Fix npm cache directory permissions
        sh 'npm config set cache /home/ubuntu/.npm'
        sh 'mkdir -p /home/ubuntu/.npm && chown -R $(whoami) /home/ubuntu/.npm'
      }
    }
  stages {
    stage('Build') {
      steps {
        sh 'npm install'
      }
    }
    stage('Test') {
      environment {
        CI = 'true'
      }
      steps {
        sh './jenkins/scripts/test.sh'
      }
    }
    stage('Deliver') {
      steps {
        sh './jenkins/scripts/deliver.sh'
        input 'Finished using the web site? (Click "Proceed" to continue)'
        sh './jenkins/scripts/kill.sh'
      }
    }
  }
}
